// ============================================================
// Data Memory
// ============================================================
// This module implements the CPU's data memory.
//
// It supports two basic operations:
//
// 1. LOAD  -> read data from memory
// 2. STORE -> write data into memory
//
// For your first single-cycle RISC-V CPU, we are supporting
// word accesses (32 bits).
// ============================================================

module data_memory(

    // Clock used for synchronous memory writes
    input logic clk,

    // Control signal from the control unit
    // 1 = read from memory
    input logic MemRead,

    // Control signal from the control unit
    // 1 = write to memory
    input logic MemWrite,

    // 32-bit byte address generated by the ALU
    input logic [31:0] address,

    // Data coming from the register file
    // This is the value that will be stored during SW
    input logic [31:0] write_data,

    // Data coming out of memory during LW
    output logic [31:0] read_data

);


    // ========================================================
    // Memory Array
    // ========================================================
    // 256 entries
    // Each entry is 32 bits wide
    //
    // 256 words * 4 bytes = 1024 bytes = 1 KB
    //
    // memory[0]  -> first 32-bit word
    // memory[1]  -> second 32-bit word
    // memory[2]  -> third 32-bit word
    // ...
    // memory[255] -> last word
    // ========================================================

    logic [31:0] memory [0:255];


    // ========================================================
    // Initialize Memory
    // ========================================================
    // For simulation, initialize every location to zero.
    //
    // This is useful for your EDA Playground testing.
    // ========================================================

    initial begin

        integer i;

        for (i = 0; i < 256; i = i + 1) begin

            memory[i] = 32'b0;

        end

    end


    // ========================================================
    // Memory Read
    // ========================================================
    // This is an asynchronous read.
    //
    // When MemRead = 1:
    //
    //     read_data = memory[address[31:2]]
    //
    // Why [31:2]?
    //
    // Each memory location contains 4 bytes (32 bits).
    //
    // Therefore:
    //
    // Address 0x00 -> memory[0]
    // Address 0x04 -> memory[1]
    // Address 0x08 -> memory[2]
    // Address 0x0C -> memory[3]
    //
    // The bottom two address bits are not needed because
    // every word is 4-byte aligned.
    // ========================================================

    always_comb begin

        if (MemRead)

            read_data = memory[address[31:2]];

        else

            read_data = 32'b0;

    end


    // ========================================================
    // Memory Write
    // ========================================================
    // This is a synchronous write.
    //
    // Data is written only on the rising edge of the clock.
    //
    // When:
    //
    //     MemWrite = 1
    //
    // the following happens:
    //
    //     memory[address[31:2]] <= write_data;
    //
    // This is what happens during an SW instruction.
    // ========================================================

    always_ff @(posedge clk) begin

        if (MemWrite)

            memory[address[31:2]] <= write_data;

    end


endmodule